### ISSUE TITLE
Muito obrigado!

### ISSUE THREAD

**Issue by guilhermeivo** [dr2pedro/Tesa-GeoTracker#4]

**Comment by guilhermeivo** [comment]
@BaseTech-Inc agradece

**Comment by dr2pedro** [comment]
> @BaseTech-Inc agradece

Lá no CodePlayData tem algo mais atualizado, mas é em Javascript.

**Comment by guilhermeivo** [comment]
> > @BaseTech-Inc agradece
> 
> Lá no CodePlayData tem algo mais atualizado, mas é em Javascript.

**Comment by guilhermeivo** [comment]
Desculpe perguntar.
Poderia enviar o link com o conteúdo mais atualizado?

**Comment by dr2pedro** [comment]
> Desculpe perguntar.
> Poderia enviar o link com o conteúdo mais atualizado?

Esse é o mais recente aqui no Github:
https://github.com/CodePlayData/tesa

Mas atualmente eu tenho usado o Gitlab por causa do CI/CD então pretendo na semana que vem liberar uma nova versão desse mesmo projeto com a parte de geolocalização já. Se quiser acompanhar fica ligado lá que aqui no Github eu devo só copiar e colar bem depois de publicar lá antes.

https://gitlab.com/codeplaydata

**Comment by guilhermeivo** [comment]
Continue com o bom trabalho, Pedrão!
